### ISSUE TITLE
[ENTREGA PARCIAL]

### ISSUE THREAD

**Issue by jpetito** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-jpetito#1]
@juanFdS

**Comment by JuanFdS** [comment]
Parte A
---

- Falta limitar el poder innato entre 1 y 10
- Se puede extraer cierta lógica repetida entre aprendiz y veterano usando algún coeficiente, pero está bien
- Se podría hacer más declarativo lo de que el nombre sea par, e iría con % en vez de / para el resto.

Parte B
---

- Bien la validación en el initialize!
- Al sumarle al líder se deberían multiplicar los puntos por la cantidad de miembros del gremio derrotado (o queda así si es un mago).
- No hace falta preguntar si es gremio es o no para el líder, ya que los magos no tienen líder.

Nota: 9
